"""Add openrouter key

Revision ID: 43e5d6d65512
Revises: c2d3e4f5a6b7
Create Date: 2026-02-21 13:40:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '43e5d6d65512'
down_revision = 'c2d3e4f5a6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('encrypted_openrouter_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('openrouter_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'openrouter_api_key')
    op.drop_column('user', 'encrypted_openrouter_key')
    # ### end Alembic commands ###
