"""Add intelligence fields

Revision ID: 483b95feeaec
Revises: e09fbedcbe75
Create Date: 2026-03-06 23:44:25.299694

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '483b95feeaec'
down_revision = 'e09fbedcbe75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readinginsight', sa.Column('hook', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('readinginsight', sa.Column('before', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('readinginsight', sa.Column('after', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('readinginsight', sa.Column('why_it_matters', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readinginsight', 'why_it_matters')
    op.drop_column('readinginsight', 'after')
    op.drop_column('readinginsight', 'before')
    op.drop_column('readinginsight', 'hook')
    # ### end Alembic commands ###
