"""Add clerk_id to User

Revision ID: 9d094e8f561b
Revises: 483b95feeaec
Create Date: 2026-03-07 11:52:21.263847

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9d094e8f561b'
down_revision = '483b95feeaec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotencyrecord',
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_idempotencyrecord_idempotency_key'), 'idempotencyrecord', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_idempotencyrecord_user_id'), 'idempotencyrecord', ['user_id'], unique=False)
    op.add_column('user', sa.Column('clerk_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_user_clerk_id'), 'user', ['clerk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_clerk_id'), table_name='user')
    op.drop_column('user', 'clerk_id')
    op.drop_index(op.f('ix_idempotencyrecord_user_id'), table_name='idempotencyrecord')
    op.drop_index(op.f('ix_idempotencyrecord_idempotency_key'), table_name='idempotencyrecord')
    op.drop_table('idempotencyrecord')
    # ### end Alembic commands ###
