"""make_idempotency_record_user_id_nullable
 
Revision ID: d7fff4421d11
Revises: 9d094e8f561b
Create Date: 2026-03-07 14:00:00.000000
 
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
 
 
# revision identifiers, used by Alembic.
revision = 'd7fff4421d11'
down_revision = '9d094e8f561b'
branch_labels = None
depends_on = None
 
 
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idempotencyrecord', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
 
 
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idempotencyrecord', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
