"""add_intelligence_keywords_to_user

Revision ID: e09fbedcbe75
Revises: f6d439676745
Create Date: 2026-02-28 13:16:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e09fbedcbe75'
down_revision = 'f6d439676745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('intelligence_keywords', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'intelligence_keywords')
    # ### end Alembic commands ###
