"""add wisdom, reading, and insights tables

Revision ID: f6d439676744
Revises: f1a2b3c4d5e6
Create Date: 2026-02-21 15:39:46.306216

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f6d439676744'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wisdom',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('book', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('key_lesson', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('how_to_apply', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('is_bookmarked', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readinginsight',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('content_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('key_takeaways', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actionable_advice', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('read_time_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readinginsight')
    op.drop_table('reading')
    op.drop_table('wisdom')
    # ### end Alembic commands ###
